package org.familysearch.logging.scanner;

import org.junit.jupiter.api.Test;
import spoon.Launcher;
import spoon.reflect.declaration.CtType;
import spoon.support.compiler.VirtualFile;

import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Collections;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

class LoggerFieldProcessorTest {

    private ScannerConfig createTestConfig() {
        return new ScannerConfig(
            Paths.get("."),
            Paths.get("/tmp/output.json"),
            false,
            Collections.emptyList(),
            false
        );
    }

    private List<LoggerCandidate> processJavaCode(String javaCode) {
        Launcher launcher = new Launcher();
        launcher.addInputResource(new VirtualFile(javaCode));
        launcher.getEnvironment().setNoClasspath(true);
        launcher.getEnvironment().setAutoImports(true);
        launcher.getEnvironment().setCommentEnabled(false);
        launcher.getEnvironment().setComplianceLevel(17);
        launcher.buildModel();

        LoggerFieldProcessor processor = new LoggerFieldProcessor(createTestConfig());
        launcher.addProcessor(processor);
        launcher.process();

        return processor.getCandidates();
    }

    @Test
    void shouldDetectLoggerFieldByTypeName() {
        String javaCode = """
            package com.example;
            import org.slf4j.Logger;
            import org.slf4j.LoggerFactory;

            public class Service {
                private static final Logger LOGGER = LoggerFactory.getLogger(Service.class);
            }
            """;

        List<LoggerCandidate> candidates = processJavaCode(javaCode);

        assertEquals(1, candidates.size());
        LoggerCandidate candidate = candidates.get(0);
        assertEquals(CandidateType.LOGGER_DECLARATION, candidate.getType());
        assertEquals("LOGGER", candidate.getName());
        assertFalse(candidate.isNeedsValidation());
        assertEquals("type_name", candidate.getDetectionStrategy());
    }

    @Test
    void shouldDetectLoggerFieldWithSimpleLoggerType() {
        String javaCode = """
            package com.example;

            public class Service {
                private Log log;
            }
            """;

        List<LoggerCandidate> candidates = processJavaCode(javaCode);

        assertEquals(1, candidates.size());
        assertEquals("log", candidates.get(0).getName());
    }

    @Test
    void shouldDetectLoggerByImportStatement() {
        String javaCode = """
            package com.example;
            import org.slf4j.Logger;

            public class Service {
                private Logger myLogger;
            }
            """;

        List<LoggerCandidate> candidates = processJavaCode(javaCode);

        assertEquals(1, candidates.size());
        assertEquals("myLogger", candidates.get(0).getName());
        assertEquals("type_name", candidates.get(0).getDetectionStrategy());
    }

    @Test
    void shouldDetectLoggerByLoggerFactoryPattern() {
        String javaCode = """
            package com.example;

            public class Service {
                private Object logger = LoggerFactory.getLogger(Service.class);
            }
            """;

        List<LoggerCandidate> candidates = processJavaCode(javaCode);

        assertEquals(1, candidates.size());
        assertEquals("logger", candidates.get(0).getName());
        assertEquals("logger_factory_pattern", candidates.get(0).getDetectionStrategy());
    }

    @Test
    void shouldDetectLombokSlf4jAnnotation() {
        String javaCode = """
            package com.example;
            import lombok.extern.slf4j.Slf4j;

            @Slf4j
            public class Service {
                public void doSomething() {
                    // log field is generated by Lombok
                }
            }
            """;

        // Note: Lombok generates the 'log' field at compile time, not in the AST
        // This test verifies we can detect the @Slf4j annotation
        Launcher launcher = new Launcher();
        launcher.addInputResource(new VirtualFile(javaCode));
        launcher.getEnvironment().setNoClasspath(true);
        launcher.getEnvironment().setComplianceLevel(17);
        launcher.buildModel();

        CtType<?> type = launcher.getModel().getAllTypes().iterator().next();
        boolean hasSlf4jAnnotation = type.getAnnotations().stream()
            .anyMatch(ann -> ann.toString().contains("Slf4j"));

        assertTrue(hasSlf4jAnnotation);
    }

    @Test
    void shouldNotDetectNonLoggerFields() {
        String javaCode = """
            package com.example;

            public class Service {
                private String name;
                private int count;
                private Object data;
            }
            """;

        List<LoggerCandidate> candidates = processJavaCode(javaCode);

        assertEquals(0, candidates.size());
    }

    @Test
    void shouldDetectMultipleLoggerFields() {
        String javaCode = """
            package com.example;
            import org.slf4j.Logger;
            import org.slf4j.LoggerFactory;

            public class Service {
                private static final Logger LOGGER = LoggerFactory.getLogger(Service.class);
                private Logger instanceLogger = LoggerFactory.getLogger("instance");
            }
            """;

        List<LoggerCandidate> candidates = processJavaCode(javaCode);

        assertEquals(2, candidates.size());
        assertTrue(candidates.stream().anyMatch(c -> "LOGGER".equals(c.getName())));
        assertTrue(candidates.stream().anyMatch(c -> "instanceLogger".equals(c.getName())));
    }

    @Test
    void shouldExtractCorrectSourcePosition() {
        String javaCode = """
            package com.example;
            import org.slf4j.Logger;

            public class Service {
                private static final Logger LOGGER = null;
            }
            """;

        List<LoggerCandidate> candidates = processJavaCode(javaCode);

        assertEquals(1, candidates.size());
        LoggerCandidate candidate = candidates.get(0);
        assertEquals(5, candidate.getLine());
        assertTrue(candidate.getColumn() > 0);
    }

    @Test
    void shouldExtractFullyQualifiedTypeName() {
        String javaCode = """
            package com.example;
            import org.slf4j.Logger;

            public class Service {
                private Logger LOGGER;
            }
            """;

        List<LoggerCandidate> candidates = processJavaCode(javaCode);

        assertEquals(1, candidates.size());
        // In noclasspath mode, we may not get fully qualified names
        assertNotNull(candidates.get(0).getTypeName());
    }

    @Test
    void shouldHandleStaticLoggerFields() {
        String javaCode = """
            package com.example;
            import org.slf4j.Logger;

            public class Service {
                private static Logger LOGGER;
            }
            """;

        List<LoggerCandidate> candidates = processJavaCode(javaCode);

        assertEquals(1, candidates.size());
        assertEquals("LOGGER", candidates.get(0).getName());
    }

    @Test
    void shouldHandleFinalLoggerFields() {
        String javaCode = """
            package com.example;
            import org.slf4j.Logger;

            public class Service {
                private final Logger logger = null;
            }
            """;

        List<LoggerCandidate> candidates = processJavaCode(javaCode);

        assertEquals(1, candidates.size());
        assertEquals("logger", candidates.get(0).getName());
    }

    @Test
    void shouldHandlePublicLoggerFields() {
        String javaCode = """
            package com.example;
            import org.slf4j.Logger;

            public class Service {
                public Logger LOGGER;
            }
            """;

        List<LoggerCandidate> candidates = processJavaCode(javaCode);

        assertEquals(1, candidates.size());
        assertEquals("LOGGER", candidates.get(0).getName());
    }
}
